export const arabCountries = [
  { name: 'مصر', code: 'EG', currency: 'EGP', flag: '🇪🇬' },
  { name: 'السعودية', code: 'SA', currency: 'SAR', flag: '🇸🇦' },
  { name: 'الإمارات', code: 'AE', currency: 'AED', flag: '🇦🇪' },
  { name: 'قطر', code: 'QA', currency: 'QAR', flag: '🇶🇦' },
  { name: 'الكويت', code: 'KW', currency: 'KWD', flag: '🇰🇼' },
  { name: 'البحرين', code: 'BH', currency: 'BHD', flag: '🇧🇭' },
  { name: 'عمان', code: 'OM', currency: 'OMR', flag: '🇴🇲' },
  { name: 'الأردن', code: 'JO', currency: 'JOD', flag: '🇯🇴' },
  { name: 'لبنان', code: 'LB', currency: 'LBP', flag: '🇱🇧' },
  { name: 'سوريا', code: 'SY', currency: 'SYP', flag: '🇸🇾' },
  { name: 'العراق', code: 'IQ', currency: 'IQD', flag: '🇮🇶' },
  { name: 'اليمن', code: 'YE', currency: 'YER', flag: '🇾🇪' },
  { name: 'فلسطين', code: 'PS', currency: 'ILS', flag: '🇵🇸' },
  { name: 'تونس', code: 'TN', currency: 'TND', flag: '🇹🇳' },
  { name: 'الجزائر', code: 'DZ', currency: 'DZD', flag: '🇩🇿' },
  { name: 'المغرب', code: 'MA', currency: 'MAD', flag: '🇲🇦' },
  { name: 'ليبيا', code: 'LY', currency: 'LYD', flag: '🇱🇾' },
  { name: 'السودان', code: 'SD', currency: 'SDG', flag: '🇸🇩' },
  { name: 'الصومال', code: 'SO', currency: 'SOS', flag: '🇸🇴' },
  { name: 'جيبوتي', code: 'DJ', currency: 'DJF', flag: '🇩🇯' },
  { name: 'موريتانيا', code: 'MR', currency: 'MRU', flag: '🇲🇷' },
  { name: 'جزر القمر', code: 'KM', currency: 'KMF', flag: '🇰🇲' },
];
